# Exported from Render on 2025-11-20T18:43:30Z
version: "1"
services:
- type: web
  name: n8n
  runtime: docker
  repo: https://github.com/danny-garxia/n8n-render-deploy
  plan: free
  envVars:
- key: N8N_HOST
        value: ${{render.services[0].url}}
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://${{render.services[0].url}}/
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: danny                 # change this to whatever username you want
      - key: N8N_BASIC_AUTH_PASSWORD
        value: YourSuperStrongPass123!   # CHANGE THIS to a strong password
      - key: EXECUTIONS_MODE
        value: queue
      - key: N8N_ENCRYPTION_KEY
        generateValue: true          # auto-generates a secure key every deploy
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit

databases:
  - name: n8n-postgres
    plan: free
    region: oregon
